version: "3"
services:
  app:
    container_name: devfinances
    build:
      context: .
      args:
        USER: docker
        UID: 1000
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    working_dir: /usr/src/app
    environment:
      SERVICE_NAME: devfinances
      DB_CONNECTION: mysql
      DB_DRIVER: mysql
      DB_HOST: mysql
      DB_PORT: 3306
    networks:
      - network

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx/.
    volumes:
      - "./public:/usr/src/app/public"
    environment:
      NGINX_FPM_HOST: app
      NGINX_ROOT: /usr/src/app/public
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - network

  mysql:
    container_name: mysql
    build:
      context: ./docker/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - "./.docker/mysql:/var/lib/mysql"
    networks:
      - network

  phpmyadmin:
    container_name: phpmyadmin
    build: ./docker/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "8000:80"
    depends_on:
      - mysql
    networks:
      - network

  redis:
    container_name: redis
    build: ./docker/redis
    volumes:
      - "./.docker/redis:/data/redis"
    ports:
      - "6379:6379"
    networks:
      - network

  maildev:
    container_name: maildev
    build: ./docker/maildev
    ports:
      - "1080:80"
      - "25:25"
    networks:
      - network

networks:
  network:
    driver: bridge
